### ISSUE TITLE
I can't open any graphics test and any games

### ISSUE THREAD

**Issue by Presx2FForRespect** [Herick75/Box4Droid#2]
I can't open the graphics test.  DirectX error appears.  Although I installed .turnip_14.03.23+zink_11.06.22_fix.  And the problem is not resolved

No root

Android 12

Snapdragon 845

**Comment by JonJonesBR** [comment]
Could this error be related to phantom process killer on Android 11, 12, 13...??

**Comment by Herick75** [comment]
This is very strange, I don't know if this has anything to do with the Phantom Killer. I don't have any devices with Android 12 to test (my 2 devices use Android 11) so there's no way I can give you an accurate diagnosis, what I recommend is If you redo the process, if the error still persists, wait for the next Rootfs updates.

**Comment by Presx2FForRespect** [comment]
I reinstalled it a second time and it didn't solve the problem

**Comment by Herick75** [comment]
We already know that your processor is compatible with Turnip, so what we can conclude is maybe the Rom you were using is not compatible, or there is something wrong with the RootFS, in this case I recommend you to wait for the next version of RootFS, I I'm going to make some changes regarding the installation of the Turnip and Zink drivers, and maybe it will work on your device.
You said you put Alexvorxx's Turnip and Zink, they didn't work here, because Box86 only uses armhf and arm64 drivers, so that way it won't read drivers compiled in i386.

**Comment by headshot2017** [comment]
try using any of the DXVK 1.10 versions and put your game in the C: drive. i was able to get nfs:mw, trackmania and a few others working with this

**Comment by Brucelee23** [comment]
Android 12 not work

**Comment by Fl4shb4ng** [comment]
What ROM are you using? AOSP?

**Comment by Presx2FForRespect** [comment]
Yes its Pixel 3

**Comment by Presx2FForRespect** [comment]
> What ROM are you using? AOSP?

Yes its Pixel 3

**Comment by Brucelee23** [comment]
realme ui 3.0 , Android 12, I'm using international straw sd870


Vào 0:24, CN, 23 thg 4, 2023 Presx2FForRespect ***@***.***>
đã viết:

**Comment by Brucelee23** [comment]
the game started but it crashed after that

**Comment by Herick75** [comment]
New version released,please update to the New Rootfs

**Comment by Presx2FForRespect** [comment]
> New version released,please update to the New Rootfs

Okey

**Comment by Presx2FForRespect** [comment]
> New version released,please update to the New Rootfs

Working now . Thanks and I hope you have a Discord community
